### ISSUE TITLE
Support linuxArm64

### ISSUE THREAD

**Issue by hfhbd** [hfhbd/postgres-native-sqldelight#102]
Mostly for arm docker
Needs upstream support, starting with coroutines: https://github.com/Kotlin/kotlinx.coroutines/pull/2841#issuecomment-1298377277

**Comment by hfhbd** [comment]
Needs https://github.com/ktorio/ktor/pull/3587

**Comment by hfhbd** [comment]
I use the native network library `ktor-network` to listen the socket for remote notifications. Of course I could simply copy this code, I did this in the past, the code contains only a few files, but I have a local draft to implement the driver without libpq by using the postgres network protocol. This implementation requires https and so ktor cio http client.

**Comment by bcmedeiros** [comment]
Makes sense!
