### ISSUE TITLE
0.0.6 not released for dialect

### ISSUE THREAD

**Issue by nomisRev** [hfhbd/postgres-native-sqldelight#139]
Hey @hfhbd,
Thanks for the amazing work you're putting into this library 🙏 👏 
This alongside the Postgres efforts in SqlDelight are my favourite upcoming functionality in the KMP eco-system!

I was updating to the latest version, and noticed that only `driver` was released for `0.0.6`.
Unsure if this was intentionally, or accidentally. If this was intentional feel free to close this issue ☺️

**Comment by hfhbd** [comment]
Of course, this was not intentional, thanks for the issue, will publish it now.

Keep in mind, until now, this is only a single-threaded wrapper over libpq using 1 connection only. There is no connection pool nor a "good" multithread support (like JDBC or R2DBC).

**Comment by nomisRev** [comment]
> Keep in mind, until now, this is only a single-threaded wrapper over libpq using 1 connection only.

Thanks for mentioning, so far I am only playing with the implementation in an example project 👍

**Comment by hfhbd** [comment]
Should be published with 0.0.7
