### ISSUE TITLE
CURSOR FOR INSERT

### ISSUE THREAD

**Issue by hfhbd** [hfhbd/postgres-native-sqldelight#6]

**Comment by hfhbd** [comment]
I do understand the second error: `cursor-226892384` because the dash is not a valid cursor name, but what is wrong with the first case?

**Comment by hfhbd** [comment]
Thanks, I fixed the first issue.
I will create another issue with the second issue, `CURSOR FOR INSERT`.

**Comment by hfhbd** [comment]
> I have two failing test cases, are you interested in 2 PRs or 2 issue tickets?
both are okay, failing PRs with the issue too!

**Comment by hfhbd** [comment]
Current workaround is unsafe, because it checks for `if (sql.startsWith("INSERT")`. But your SQL could start with `WITH`.

https://github.com/cashapp/sqldelight/issues/3599

**Comment by nomisRev** [comment]
Not perfect either, but would `contains` work here? It looks for the _first_ occurrence of `INSERT` within the entire `sql: String` so it would also return `true` for statements start with `WITH`.

`contains` is delegated to a native call in the Kotlin Std in this case, so it gives me the impression that it's even more optimised than the Kotlin Std `contains`.

**Comment by hfhbd** [comment]
It depends on your SQL query :D `SELECT * FROM foo WHERE "INSERTING" IN bar` would match too, that's why I used `startsWith`. Ideally, this should be fixed in sqldelight, which parses the query.

**Comment by nomisRev** [comment]
Right... I guess even using a `Regex` like `private val insertRegex = "\\sINSERT\\s".toRegex()` might not cover all these cases, it covers the case you mention above 😅 Combined with `contains` it would look for the first occurrence of `INSERT` prefixed with a whitespace `\s` and ends with a whitespace `\s`.

Assuming that `INSERT` is not valid, besides for actual `INSERT` queries it would be fine but with more complex queries like nested queries or `WITH` queries this could still match incorrectly.

> Ideally, this should be fixed in sqldelight, which parses the query.
💯, but not so familiar with the internals of SqlDelight yet. I'd guess you'd want a separate type for `Insert` besides `ExecutableQuery`.

**Comment by hfhbd** [comment]
> I'd guess you'd want a separate type for Insert besides ExecutableQuery

Yes, not a new query type but I think a new driver method should work. 

> Not sure how the sqldelight team feels about that.

I feel good with this change :D

**Comment by hfhbd** [comment]
> Or could this be handled by the dialect module 

Not yet, sqldelight lacks a code generating compiler API. Don't have time to implement it now
